name: pomodoro_timer
description: Creating Pomodoro timer with many features.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.2.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.1.2
  flutter_local_notifications: ^14.1.1
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^7.1.1
  mockito: ^5.4.0
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/languages/

  fonts:
      - family: Raleway
        fonts:
          - asset: assets/fonts/Raleway-Medium.ttf
            weight: 500
          - asset: assets/fonts/Raleway-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Raleway-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Raleway-Black.ttf
            weight: 900
